---
- name: Testing Script
  hosts: all

  become: true

  tasks:
    - name: test cmd
      ansible.builtin.shell: apt install curl -y && mkdir -p /krabs-data/krabs-scripts/ansible/ && cd /krabs-data/krabs-scripts/ansible/ && curl -o /krabs-data/krabs-scripts/ansible/alert_disk_space.sh https://raw.githubusercontent.com/krabs-github/ansible/refs/heads/main/alert_disk_space.sh && chmod 755 /krabs-data/krabs-scripts/ansible/alert_disk_space.sh && /krabs-data/krabs-scripts/ansible/alert_disk_space.sh
      args:
        executable: /bin/bash