---
- name: Check for Reboot
  hosts: all

  become: true

  tasks:
   - name: Check if reboot required
     stat:
      path: /var/run/reboot-required
     register: reboot_required_file

   - name: Reboot if required
     reboot:
      async: 0
      poll: 0
      ignore_errors: yes
     when: reboot_required_file.stat.exists == true