---
- name: System Cleanup and Maintenance
  hosts: all
  become: true
  
  tasks:
    # ---------------------------------------------------------
    # 1. REMOVE OLD KERNELS
    # ---------------------------------------------------------
    - name: Identify old kernels (excluding the running one)
      ansible.builtin.shell: |
        IN_USE=$(uname -r)
        dpkg --list | \
        grep -v "$IN_USE" | \
        grep -Ei 'linux-image|linux-headers|linux-modules' | \
        awk '{ print $2 }'
      register: old_kernels
      changed_when: false
      args:
        executable: /bin/bash

    - name: Purge old kernels identified
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
        purge: true
      loop: "{{ old_kernels.stdout_lines | default([]) }}"
      when: old_kernels.stdout_lines | length > 0
      register: kernel_result

    # ---------------------------------------------------------
    # 2. CLEAN LOGS
    # ---------------------------------------------------------
    - name: Rotate systemd journal
      ansible.builtin.command: journalctl --rotate
      changed_when: true

    - name: Vacuum systemd journal (keep 3 days)
      ansible.builtin.command: journalctl --vacuum-time=3d
      register: vacuum_output
      # Using default('') prevents errors if stderr is missing
      changed_when: "'0B' not in vacuum_output.stderr | default('')"

    # ---------------------------------------------------------
    # 3. REMOVE SNAPS
    # ---------------------------------------------------------
    - name: Remove disabled Snap revisions
      ansible.builtin.shell: |
        set -eu
        # Check if snap command exists first to avoid shell errors
        if command -v snap &> /dev/null; then
            snap list --all | awk '/disabled/{print $1, $3}' |
            while read snapname revision; do
                snap remove "$snapname" --revision="$revision"
                echo "Removed $snapname revision $revision"
            done
        else
            echo "Snap not installed"
        fi
      args:
        executable: /bin/bash
      register: snap_clean
      changed_when: "'Removed' in snap_clean.stdout"
      ignore_errors: true

    # ---------------------------------------------------------
    # 4. APT CLEAN
    # ---------------------------------------------------------
    - name: Autoremove unused dependencies
      ansible.builtin.apt:
        autoremove: true
        purge: true
      register: apt_autoremove

    - name: Clean apt cache
      ansible.builtin.apt:
        clean: true
      register: apt_clean

    # ---------------------------------------------------------
    # 5. COMPILE & OUTPUT STATISTICS
    # ---------------------------------------------------------
    - name: Display Cleanup Statistics
      ansible.builtin.debug:
        msg: 
          - "=========================================="
          - " SYSTEM CLEANUP REPORT: {{ inventory_hostname }}"
          - "=========================================="
          - "1. Kernels Removed : {{ old_kernels.stdout_lines | default([]) | length }}"
          # The regex logic below is now wrapped in (...) or ['0B'] to handle 'None' results safely
          - "2. Journal Freed   : {{ (vacuum_output.stderr | default('') | regex_search('freed (.*?) of', '\\1') or ['0B']) | first }}"
          - "3. Snaps Removed   : {{ snap_clean.stdout_lines | default([]) | select('search', 'Removed') | list | length }}"
          - "4. Apt Autoremove  : {{ 'Changed' if apt_autoremove.changed else 'No changes' }}"
          - "=========================================="