---
- name: Flush RAM Cache Immediately on Host
  hosts: all
  become: true

  tasks:
    - name: Run sync and drop caches
      ansible.builtin.shell: "sync && echo 3 > /proc/sys/vm/drop_caches"
      changed_when: true
