---
- name: Configure Ubuntu VM - QEMU Agent and fstrim
  hosts: all
  become: true
  tasks:
    - name: Ensure qemu-guest-agent is installed
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      notify: Start qemu service

    - name: Ensure fstrim.timer service is enabled and started
      ansible.builtin.systemd:
        name: fstrim.timer
        enabled: true
        state: started

  handlers:
    - name: Start qemu service
      ansible.builtin.systemd:
        name: qemu-guest-agent
        state: started
        enabled: false  # Crucial: Keeps systemd from throwing the install/static error
