---
- name: Testing Script
  hosts: all

  become: true

  tasks:
    - name: test cmd
      ansible.builtin.shell: 
      cmd: ls -l /krabs-data > /krabs-data/test.txt
      args:
        executable: /bin/bash