---
- name: Update PiHole
  hosts: all

  become: true

  tasks:
    - name: Update PiHole
      command: pihole updatePihole

    - name: Update Gravity
      command: pihole updateGravity
