---
- name: Update Portainer Agent
  hosts: all

  become: true

  tasks:
    - name: Stop Portainer Agent
      command: docker stop portainer_agent
      ignore_errors: yes

    - name: Remove Old Portainer Agent
      command: docker rm portainer_agent
      ignore_errors: yes

    - name: Update Portainer Agent Image
      command: docker pull portainer/agent

    - name: Start Portainer Agent
      command: >
        docker run -d
        -p 9001:9001
        --name=portainer_agent
        --restart=always
        -v /var/run/docker.sock:/var/run/docker.sock
        -v /var/lib/docker/volumes:/var/lib/docker/volumes
        portainer/agent